### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'fieldName')

### ISSUE THREAD

**Issue by moayidalsubhi** [stephanrauh/ngx-extended-pdf-viewer#1648]
I keep getting this exception when trying to read form data of dropdown. 

Uncaught TypeError: Cannot read properties of undefined (reading 'fieldName')
    at HTMLSelectElement.<anonymous> (viewer-3.2.506.min.js:23:217748)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at HTMLSelectElement.globalZoneAwareCallback (zone.js:1725:16)

I am on : 
angular: 14.2.9
"ngx-extended-pdf-viewer": "^16.0.0-alpha.2"

[Video](https://user-images.githubusercontent.com/29224400/212269339-476c19fd-333d-48b6-b887-d9ae8cb72e79.mov)

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 16.0.0-alpha.3.

Enjoy!
Stephan
