### ISSUE TITLE
Error on 18.0.0-beta.0

### ISSUE THREAD

**Issue by jpike88** [stephanrauh/ngx-extended-pdf-viewer#1827]
Since upgrading from `17.0.0-alpha.4` to `18.0.0-beta.0` I'm getting weird error... it seems to work ok otherwise though.

```
Error: Uncaught (in promise): TypeError: d.unregister is not a function
TypeError: d.unregister is not a function
    at https://app.aquipa.com/assets/viewer-3.9.601.min.js:44:309866
    at tt.invoke (https://app.aquipa.com/vendor.afbe4d551b944ba0.js:1:3762...
```

**Comment by stephanrauh** [comment]
It seems I've forgotten to close the ticket after solving it.
