### ISSUE TITLE
Printing dialog doesn't work/show in Chrome, does work/show in Firefox

### ISSUE THREAD

**Issue by johnmanko** [stephanrauh/ngx-extended-pdf-viewer#1892]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).

NO

- Does the bug also happen on https://pdfviewer.net/simple?

NO

- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.

I'll update this issue with a demo if requested.

**Describe the bug**

When manually clicking the print button, or programmatically calling `NgxExtendedPdfViewerComponent.print`, the print dialog in Chrome/Chromium `117.0.5938.88 (Official Build) snap (64-bit)` never opens after the pdf is "prepared for printing" progress complete.  When clicking on the print button a second time, an error is thrown.

This works in Firefox 117.0.1. 

I place the viewer component in a PrimeNg modal, but I don't see that as the issue (again, works in Firefox):

(I added `[replaceBrowserPrint]="false"` in an attempt to fix this issue, but it didn't work)

```html

       <p-button label="Print" (onClick)="print()"></p-button>

        <p-dialog [(visible)]="printUrl"
	          [style]="{ width: '95vw', height: '95vh' }"
	 	  onHide="pdfHide()">

		<ngx-extended-pdf-viewer
		*ngIf="printUrl"
		[replaceBrowserPrint]="false"
		[src]="printUrl"
		[showOpenFileButton]="false"
		[showDownloadButton]="false"
		[showPropertiesButton]="false"
		(pagesLoaded)="pagesLoaded()"></ngx-extended-pdf-viewer>

	</p-dialog>
```

```typescript
       print() {
              this.printUrl = 'https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf';
       }
	pdfHide() {
		this.printUrl = null;
                // Uncommenting this line has no effect
		//this.pdfViewer.ngOnDestroy();
	}

	pagesLoaded() {
		// Uncommenting this line has no effect
		//this.printService.print();
	}
```

Result:

First time clicking "print": shows "Preparing document for printing", no print dialog appears, no error:

![pdf-error-1](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3154748/881001fa-4227-4229-8b01-223c8c636d00)

Second time clicking "print": no "Preparing document for printing",  no print dialog, error:

![pdf-error-2](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3154748/6d90ffd1-a19b-4636-8bd2-6f54f561fccd)

Error:
```
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:4200/apecs/assets/viewer-3.10.547.min.js:44" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">viewer-3.10.547.min.js:44</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: The overlay does not exist.
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at OverlayManager.open (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:4200/apecs/assets/viewer-3.10.547.min.js:44:73324" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">viewer-3.10.547.min.js:44:73324</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="http://localhost:4200/apecs/assets/viewer-3.10.547.min.js:44:312408" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">viewer-3.10.547.min.js:44:312408</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invoke (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:368:26" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:368:26</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Zone.run (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:129:43" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:129:43</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:1257:36" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:1257:36</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invokeTask (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:402:31" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:402:31</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Zone.runTask (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:173:47" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:173:47</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at drainMicroTaskQueue (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="webpack:///node_modules/zone.js/fesm2015/zone.js:581:35" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">zone.js:581:35</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono,monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | open | @ | viewer-3.10.547.min.js:44
-- | -- | -- | --
  | (anonymous) | @ | viewer-3.10.547.min.js:44
  | invoke | @ | zone.js:368
  | run | @ | zone.js:129
  | (anonymous) | @ | zone.js:1257
  | invokeTask | @ | zone.js:402
  | runTask | @ | zone.js:173
  | drainMicroTaskQueue | @ | zone.js:581
  | Promise.then (async) |   |  
  | nativeScheduleMicroTask | @ | zone.js:557
  | scheduleMicroTask | @ | zone.js:568
  | scheduleTask | @ | zone.js:392
  | scheduleTask | @ | zone.js:216
  | scheduleMicroTask | @ | zone.js:236
  | scheduleResolveOrReject | @ | zone.js:1247
  | resolvePromise | @ | zone.js:1184
  | (anonymous) | @ | zone.js:1100
  | (anonymous) | @ | zone.js:1116
  | Promise.then (async) |   |  
  | (anonymous) | @ | zone.js:1489
  | ZoneAwarePromise | @ | zone.js:1411
  | Ctor.then | @ | zone.js:1488
  | printPdf | @ | viewer-3.10.547.min.js:44
  | triggerPrinting | @ | viewer-3.10.547.min.js:44
  | webViewerPrint | @ | viewer-3.10.547.min.js:44
  | dispatch | @ | viewer-3.10.547.min.js:44
  | (anonymous) | @ | viewer-3.10.547.min.js:44
  | invokeTask | @ | zone.js:402
  | runTask | @ | zone.js:173
  | invokeTask | @ | zone.js:483
  | invokeTask | @ | zone.js:1631
  | globalCallback | @ | zone.js:1674
  | globalZoneAwareCallback | @ | zone.js:1695

</span></div>
```

**Version info**
```json
    "ngx-extended-pdf-viewer": "^18.0.1",
```

**Demo PDF file**
I use the same PDF that Mozilla uses in their demo, but it also occurs with PDFs I generate in my application.

```
https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf
```

**Comment by stephanrauh** [comment]
What a strange bug! You know, printing is a surprisingly simple task: pdf.js generates a couple of images, hides your application and shows the images. That done, it calls `window.print()`. So I wonder which part of it might be browser-specific.

The error after clicking the second time is strange, too. It might be a follow-up error. Can you test this in Firefox, too? I've fixed a similar error in one of the last beta versions. If the error message shows on Firefox, too, please check if you're using the current version of pdf.js. Sometimes Angular and/or node.js cache a tad too aggressivly.

**Comment by johnmanko** [comment]
@stephanrauh 

Thanks for the quick reply!  Yes, everything works in Firefox just fine (as noted in the initial comment).  It looks like the module is using pdf.js version 3.10.547.

**Comment by stephanrauh** [comment]
OK, it's not a caching problem. You're using the most current version of pdf.js. I'm puzzled!

(But then, being puzzled is one of the recurring joys of doing open source). :)

**Comment by stephanrauh** [comment]
I forgot to mention I've got a simple demo project at https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/compatibility-tests/common/demo/src/app. On my machine, it doesn't show your bug. Obviously, I need your help to reproduce the bug.

**Comment by johnmanko** [comment]
After an update to Chrome, everything is working correctly.  I'll close this issue.  Thanks for this great package!

**Comment by stephanrauh** [comment]
That's good news!
