### ISSUE TITLE
sidebarVisible bug

### ISSUE THREAD

**Issue by Jop3K** [stephanrauh/ngx-extended-pdf-viewer#1916]
Hi, i'm using version 18.0.1.

Bug can be seen/reproduced on: https://pdfviewer.net/extended-pdf-viewer/two-way-binding 

The error is caused by [(sidebarVisible)] two-way binding. Tested on my own environment and using just the input is enough to make the error show up.

Error in devtools console:
`main.d87d667e2cc53bfe.js:1  ERROR TypeError: Cannot read properties of undefined (reading 'pdfSidebar')
    at set sidebarVisible [as sidebarVisible] (main.d87d667e2cc53bfe.js:1:1395371)
    at Object.wo [as setInput] (main.d87d667e2cc53bfe.js:1:277384)
    at Va (main.d87d667e2cc53bfe.js:1:322805)
    at Or (main.d87d667e2cc53bfe.js:1:317558)
    at Yp (main.d87d667e2cc53bfe.js:1:330966)
    at template (672.c7e63e8c232f6614.js:1:513763)
    at Js (main.d87d667e2cc53bfe.js:1:315357)
    at Nd (main.d87d667e2cc53bfe.js:1:314143)
    at Jd (main.d87d667e2cc53bfe.js:1:321591)
    at Rd (main.d87d667e2cc53bfe.js:1:314995)`

**Comment by stephanrauh** [comment]
Until the end of the month, I'm busy, so I can't fix the bug as soon as I'd like to do. Nonetheless, I've been able to reproduce it, and usually, that's your ticket to getting your bug solved soon! :)

**Comment by stephanrauh** [comment]
Version 18.1.2 fixes this bug.
