### ISSUE TITLE
Right-click may cause exception if there's no text layer

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#2349]
Starting with pdf.js 4.3, the right-click sometimes causes an exception if there's no text layer.

Steps to reproduce:
- go to the book mode demo of the showcase: http://localhost:4200/extended-pdf-viewer/book-mode
- click the "context menu"
- right-click the PDF file

Then this error message occurs in the console:
```
polyfills.cb63d087e4ed7d72.js:1 Uncaught 
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at document.addEventListener.signal (viewer-4.3.620.min.mjs:21:209584)
    at l.invokeTask (polyfills.cb63d087e4ed7d72.js:1:19395)
    at I.runTask (polyfills.cb63d087e4ed7d72.js:1:14726)
    at _.invokeTask [as invoke] (polyfills.cb63d087e4ed7d72.js:1:20447)
    at w (polyfills.cb63d087e4ed7d72.js:1:4666)
    at j (polyfills.cb63d087e4ed7d72.js:1:5061)
    at HTMLDocument.U (polyfills.cb63d087e4ed7d72.js:1:5225)
﻿```

**Comment by stephanrauh** [comment]
The bug fix has shipped with version 20.5.0-alpha.1.
