### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'unbindWindowEvents')

### ISSUE THREAD

**Issue by hs65** [stephanrauh/ngx-extended-pdf-viewer#2439]
**Version:** 21.0.0-alpha.9
**Browser:** Chrome
**Usage:** jasmine test
**Hint:** Error did not occur in 20.5.0-alpha.4. Test has not been touched
**Error:** TypeError: Cannot read properties of undefined (reading 'unbindWindowEvents')
	    at PDFScriptLoaderService.ngOnDestroy (node_modules/ngx-extended-pdf-viewer/fesm2022/ngx-extended-pdf-viewer.mjs:1567:30)
	    at R3Injector.destroy (node_modules/@angular/core/fesm2022/core.mjs:9245:25)
	    at NgModuleRef.destroy (node_modules/@angular/core/fesm2022/core.mjs:22706:41)
	    at TestBedImpl.tearDownTestingModule (node_modules/@angular/core/fesm2022/testing.mjs:27601:33)
	    at TestBedImpl.resetTestingModule (node_modules/@angular/core/fesm2022/testing.mjs:27378:26)
	    at UserContext.apply (node_modules/@angular/core/fesm2022/testing.mjs:27713:21)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:368:26)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:273:39)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:367:52)
	    at Zone.run (node_modules/zone.js/fesm2015/zone.js:129:43)

**Comment by hs65** [comment]
I switched back to 20.0.0-alpha.4 and that error is gone. It seems not to be related to the test setup.

**Comment by stephanrauh** [comment]
Yes, you're right. Version 20.0.0-alpha.10 fixes the problem. Thanks for making me aware of it!

Best regards,
Stephan
