### ISSUE TITLE
Unable to open pdf on android 9

### ISSUE THREAD

**Issue by tanjooxiang** [stephanrauh/ngx-extended-pdf-viewer#605]
Hello, 

Not sure what the issue but im trying it use this pdf viewer in one of my app. 
I tried in android 10 and it is working perfectly, but when i try using the same code and deploy into an android 9 emulator, it is unable to open.

the only error message im seeing from the console is: 

`polyfills.f3409dca4fe730ae84f9.js:1 Unhandled Promise rejection: globalThis is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: globalThis is not defined
    at getDocument (pdf-2.6.418.js:1864)
    at Object.open (viewer-2.6.418.js:948)
    at e.openPDF (main.3ee81f39d3e5133e11c0.js:1)
    at initTimeout.setTimeout (main.3ee81f39d3e5133e11c0.js:1)
    at l.invokeTask (polyfills.f3409dca4fe730ae84f9.js:1)
    at s.runTask (polyfills.f3409dca4fe730ae84f9.js:1)
    at invokeTask (polyfills.f3409dca4fe730ae84f9.js:1)
    at invoke (polyfills.f3409dca4fe730ae84f9.js:1)
    at n.args.(/android_asset/www/checklist/98/anonymous function) (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:79039) ReferenceError: globalThis is not defined
    at getDocument (file:///android_asset/www/assets/pdf-2.6.418.js:1864:28)
    at Object.open (file:///android_asset/www/assets/viewer-2.6.418.js:948:51)
    at e.openPDF (file:///android_asset/www/main.3ee81f39d3e5133e11c0.js:1:1721012)
    at initTimeout.setTimeout (file:///android_asset/www/main.3ee81f39d3e5133e11c0.js:1:1712747)
    at l.invokeTask (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:54115)
    at s.runTask (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:49524)
    at invokeTask (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:55165)
    at invoke (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:55067)
    at n.args.(anonymous function) (file:///android_asset/www/polyfills.f3409dca4fe730ae84f9.js:1:79039)`

my dependencies are : 

`"dependencies": {
    "@angular/animations": "^9.0.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.0.0",
    "@angular/material": "^9.0.0",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/router": "^9.0.0",
    "chart.js": "^2.8.0",
    "jquery": "^3.4.1",
    "jsstore": "^3.7.6",
    "ng2-charts": "^2.3.0",
    "ngx-extended-pdf-viewer": "^7.1.0",
    "ngx-owl-carousel": "^2.0.7",
    "owl.carousel": "^2.3.4",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "watermarkjs": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },`

hopefully you have some clue to why this is happening.

Thank you.

**Comment by stephanrauh** [comment]
It's easier to diagnose if you add the attribute `[minifiedJSLibraries]="false"`. However, I guess `globalThis` is the culprit. It's a recent addition to JavaScript, so you may need to polyfill it. See https://medium.com/@susanne.lundkvist/globalthis-and-polyfill-in-javascript-ca1348e13ec and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis.

This polyfill should help you: https://www.npmjs.com/package/globalthis

**Comment by stephanrauh** [comment]
@tanjooxiang Did my answer help you? I'm closing the ticket now, but I'll still listen to it. If you've still got trouble, just tell me.

Best regards,
Stephan

**Comment by tanjooxiang** [comment]
Hello, 
Sorry. I realize that the issue might be 
`PDF.js v2.6.57(build 76c592cf5)
Message: The browser/environment lacks native support for critical functionality used by the pdf.js library. Please use an es5 build instead.`
Had initially used version "4.0.0-alpha.0" where it directly show the above error message when opening the pdf. 
However, i upgraded to 7.1.0 thinking that it might solve the problem. The above message indeed disappear but a blank screen was showing when opening the pdf. 

After a few trial and error and looking through other issue: #437 
I have preload the es-5.js in the angular.json for it to work in android 9.
`"scripts": [
              "./node_modules/ngx-extended-pdf-viewer/assets/pdf-2.6.418-es5.js",
              "./node_modules/ngx-extended-pdf-viewer/assets/pdf.worker-2.6.418-es5.js",
              "./node_modules/ngx-extended-pdf-viewer/assets/viewer-2.6.418-es5.js",
            ],`
In android 10, i didnt have to add this script.

Should I / can I continue to use this method to resolve the problem? I believe i saw you mention that it might have some performance issue? 

Thank you very much.

**Comment by stephanrauh** [comment]
Yes, if you've got a huge PDF file, you'll notice the performance penalty. Small files usually don't make trouble.

Instead of adding the pdf.worker.min.js to the angular.json, you can also set 

```typescript
import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer'; 
pdfDefaultOptions.workerSrc='/assets/pdf.worker-2.6.418-es5.min.js';
```

That solves the performance problem.

Maybe that's even enough to solve the issue, but maybe you still have to add the other files (pdf-2.6.418-es5.js and viewer-2.6.418-es5.js) to the angular.json.

Best regards,
Stephan

**Comment by tanjooxiang** [comment]
Okay thank you very much.

Appreciate it.
