### ISSUE TITLE
Unable to show PDF

### ISSUE THREAD

**Issue by sarpavardhan** [stephanrauh/ngx-extended-pdf-viewer#732]
Hi,

I am integrating ngx-extended-pdf-viewer in our application (angular 10) and i'm facing an issue and totally confused.
I'm using base64 to bind my pdf source as shown below

```
<ngx-extended-pdf-viewer
            [base64Src]="pdfSrc"
            backgroundColor="#ffffff"
            [height]="'80vh'"
            [useBrowserLocale]="true"
            [handTool]="false"
            [showHandToolButton]="false"
            [contextMenuAllowed]="false"
            [showSidebarButton]="false"
            [showFindButton]="false"
            [showOpenFileButton]="false"
            [showPrintButton]="false"
            [showRotateButton]="false"
            [showScrollingButton]="false"
            [showSpreadButton]="false"
            [showPropertiesButton]="false"
            [showBookmarkButton]="false"
        >
        </ngx-extended-pdf-viewer>
```

I see pdf loading when i try to bind the base64 string when i assign valie in ngOnInit()

`this.pdfSrc = this.getPdfData(); //getPdfData() returns string.`

```
getPdfData() {
    return "JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChDaHJvbWl1bSkKL1Byb2R1Y2VyIChTa2lhL1BERiBtODkpCi9DcmVhdGlvbkRhdGUgKEQ6MjAyMTA0MjgwNzA5MDYrMDAnMDAnKQovTW9kRGF0ZSAoRDoyMDIxMDQyODA3MDkwNiswMCcwMCcpPj4KZW5kb2JqCjMgMCBvYmoKPDwvY2EgMQovQk0gL05vcm1hbD4+CmVuZG9iago1IDAgb2JqCjw8L0ZpbHRlciAvRmxhdGVEZWNvZGUKL0xlbmd0aCAxNjY+PiBzdHJlYW0KeJxdT8sKwkAMvOcr5izYZp/tgnio2J6VBT9ArCBUsP4/mOwiiDsMmSSTkG2sS+WBBdvmJ+2SxXWhFzlmKE0KDNuJWm902eCpvcbYUGar+npl0EBxnlDFeqd2cri/Sd3RevTR66a5FFidVYhzyNSOHiYiz7Ko3GbQw1rkhXbMTs7wg/DAHCJL4U/7GjVXHSQNWh+Ffe05oX7Hpj3yg46ZToIPRWE2gwplbmRzdHJlYW0KZW5kb2JqCjIgMCBvYmoKPDwvVHlwZSAvUGFnZQovUmVzb3VyY2VzIDw8L1Byb2NTZXQgWy9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUldCi9FeHRHU3RhdGUgPDwvRzMgMyAwIFI+PgovRm9udCA8PC9GNCA0IDAgUj4+Pj4KL01lZGlhQm94IFswIDAgNjEyIDc5Ml0KL0NvbnRlbnRzIDUgMCBSCi9TdHJ1Y3RQYXJlbnRzIDAKL1BhcmVudCA2IDAgUj4+CmVuZG9iago2IDAgb2JqCjw8L1R5cGUgL1BhZ2VzCi9Db3VudCAxCi9LaWRzIFsyIDAgUl0+PgplbmRvYmoKNyAwIG9iago8PC9UeXBlIC9DYXRhbG9nCi9QYWdlcyA2IDAgUj4+CmVuZG9iago4IDAgb2JqCjw8L0xlbmd0aDEgOTEwMAovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDYwMjM+PiBzdHJlYW0KeJzNOmtUG9eZ9zESAgGSQBIMEmjkQeIhsLAENhg8jEESsnGCeMUCBxA2tnEdx9hg59XUbGInWWyv2TZ1nMaNaevT5jQ+68FJuuTRQLpJ2p40sbNN2qZ5mG3d7o+EtZsmPjlxgP3uSNg4j/b0nP2xd6SZ73W/+33fvfe73yAQRggZ0DCiaCAUarth0ysveYHyGXztTa1e3zfWPlSLEM4GPLZpR+8At56OAn474Ic27R0SpDr5U4QIB1/rloGtOwZ/LSoIcXaEkjRbewcHUDZKRkifD/LGrbfcsaWk9fUKhFKBb9rfv7m3769Pvf0K8C8Af3k/ENIdmjGEcuGL8vt3DN1e0U2eAfxFGPPmW3Zu6m2diNaBfDnwlR29tw9oinTVCDkEwIVbe3dsFsTqPwAug/zEwM7Bofl81AesTxh/YPfmAfmRjp8h5AR/yBDQmPfozZngBHtO2novsedr/5F7H6LcQTyKNAhpvqPxg6Ar/qRjqA+fxBpCtFTDaQgFzyF2i9qy1a31SEYCGtMcmgthf5ITPxtD6MT534LgKc0qZgkicCeJnma4Y/XJIRbXHGQESgpIBVAIRVAb6kWb0Ta0Aw2gQTQ2P69qWMzrR7cs8Ob/+KXXprinX940h5EFhcEyAxpQ79c1egrx7Dn/wfX3uXXzn361zn+86eKPY+iH6El0GL2FuhIM5uc2tAcoi9sL6HWgshZBnejHaOQr1J5CE8CPy8XQEfTwV8hF0EPoCfTz60aJQMzvAlueQm/hZeiXsAp2og+xDv0Tegm0fgi0G75MFUmH2xYV3LKI+jZ6hBxEawlb6w8zDvESI3oRHcfdoHkI/Dx81eOaLyi9H90N91aY670Aq02z6rPfo+T5v4JXd6O16B60GtbBtfYcPkFTYP7a0AmI6QsqzbvATArTr5GfEDL7LUD+FW2Fby8G38lhuhoFNCb8JEJysCPa3tba0hxpuvGGdY1r14QbQsFAfd1quVZaVVO9sqpyxfKKZWXepaUlhQVuV764xOnINpuMhvQ0fUqyLkmr4SjBqCQohmKC4o4pnFsMh0sZLvYCoXcRIaYIQApdL6MIMVVMuF5SBsktn5OU45LyVUlsFGpQTWmJEBQF5dWAKEzgzuYowIcDYoegzKjwDSrMuVUkDRCnE3oIwez+gKDgmBBUQnv7R4KxAOgb16fUi/WbU0pL0HiKHkA9QEqhODCOCyWsAqQwuHKcIF0aG1ahrmBvnxJpjgYDNqezo7RkjZIuBlQWqldVKtp6JUlVKWxjpqODwnjJ1MihCSPaGPOk9ol9vTdHFdoLfUdocGTkfsXkUYrEgFJ054Vs8HyzUiIGgoqHaW1suTpO47UhsaJxGUVh5GME7ogzH1xP6U1QtC7jx4iBIQjvyEhIFEIjsZHeifnhjaJgFEfGU1NHBoIQYRSJQq+J+WcO2pTQoQ7FGOvHKxPOhloalczmDVGFuEJCfy9Q4FMrOittTlPHgkzkq9gIAgHhgJg6nczxgxMy2giIMtwcjeMC2mg7g2Svp0MhMcaZWuBY2hlneIFztXtMhNlsbI2OKJxrTZ8YhBgf7FWGN8J6+hqbCtGopF+2OcWRDJNQ5e1QZQWwak3fNkHRuCEs0GtxB1gprMuIUUXSL8cfMzYYwG3KEKpEUMP0BMVgLPHZ258NCoTSEiXsiU99W1SRAwDIvYk5Co6XeaFHbwymaFtAnT7FKw4oZrHu6nwys4LbWqNql0Q3xVyvwKGc6KV4gwE2shAciQXiJjBdYnP0aeSfnx4vF2xP+FE56ggwYWs9rCt3cCTat0VxxGx9sNO2CFGbU5E7YII7xOjmDrbQIEJF0zCcUx1RIfVt0cZWsbG5M1qZMCTOYOo4V/BzasSoLa4Glpyic+mEKLHRDhA0AkEIASDW1cBdSXLp4GuEgKtUtlTraoQotqEFaTBDKRKCmwMJOYZfp1TDllN9eEGblqGgpz5sc3Y44620hABbSAwMPXQsqOEFFnVBJgAaATUqicUym615ISpuFjvEfkGRI1HmGwuPGuVEMNSYJ+aq7TpsUbAgTMgJ7AWEBVMJeWyLg6s0qPhVNPw59poFtjCiExtbR5hyMaEQgeVrFMSWsFxpsqm7n+1nMdQLmxh2tLqfR8Zlme3lfrZtR8Q1fSNia7RGlYYMcrftTjZWBmrEjW11pSWQzOrGRfxA87iMH2jtjD5thNLjgbboGYJJfayuYzwfeNGnofqSVSphVEZkiMAQpqkFEJ0qb3saCrNhlcupBBXfNIGRStMt0DDaNEHiNOMCjQCNi9NklcYazFJ2P8QY8ndQ6GPz8/WO/pFYB1vjyAoRgQ9WsChBdERpHBNtqpIibq5T9GIdo9cyem2crmX0JFgZ2IpLS+4cMQbFj7NL48clhfKEIBPCUH2xms3zf3r9AP0A137J9XL8In/6qovuS1yfsIs7rNGrV1/SMXbpCtXrZ2rth03vt758aqzHUPMxcsRrrcX17tzR2W/p0pN+j5DqaaJkgSoTkT5NO/ichJaOY+StOZPE6WZ841rNOzVnKAEQjVNG1jDymSRt8mc1ZzCj+01Ok8tpcgaIMJePj831a9o/fTzAvQpaq+c/0+yBStOI3Oh2uW0Pj/dkYn26LX17Ou2iOyipomso0VMbJck2gpPhg3A62oCsOMtaiApxrVyIhUI8UDhWOF1Ikzoj4rRIxPwebcxNxZ7UmC0D1c7MwAd7u2a6du3u7jK+19010921rKyrq7tLbbh8KfFgUx71+ySCfVwetpjTMScuYeSKFaaCCu5ky8O/O/BkXmhtY/6+p4ZWzH7yI5z2/Na2H8/Nnq66/549BadOnSKPPfjbQ4ErdxFCceO336NFoUc/+/eTc//WiQmusHGP5lRA9OENhSsCf3PQf8lrLWmutIo0akl1pVakUt4StLRbCLVkZWG9Huv09iH7fvuDdhqz44C9zU4u2PE5O24D8pP2F+2cbMf59nI7UezYPjE/JWdKwTCyG+2CnVZz0O+knar06hUrw1N2zOTMuDOindYSba0VW60oZi7jMc97zT3mnWZqNmszY8koFaemJvUkU6zt4VjsfLUzfm+XcSajytulAj5vF4ulb1fPLg+E09O1i7Xdu3cbX+vuMlV5/T1dJj+LLjZlWZxq+JwmsWAphRA7V/gBxI+dn33hxCn6P3WCsKG7LettfNCxapWDdM5etlXEQzU3+RanpXj29bG5vu+zdQJxc0LcUpETnZTvPml60kQ0Dnwg59s5RMMf4IkuheQQkp6SnWoIo067aBC94k5xn3hE1HjFWrEJkBPipHheTDKIPYCcBXBe1FYyEmHC+4DLGUQHCO8D0dOiVpeU3hnJxJm6WFqaSRMz91hpemaPKRGUGXBVXVS+bnVZ7dptfG9mWZmnO76qEmtKXVHX4uDLI7C0iEg7xabh7o393ftuEOZufHP2lROn8KeHf7q7zLvzmRGqRIYa82cPlLbdOff4XN1CSFZtH21tOTYUglXkgmi8ANHIwn+R5zVpbB3RFF2OjiQbeDxn4Jv4Hn4ff4Sf5M/z87zuEo+P8Cf4szwd4LGBdwCfngXWRZ4qPD7B42EeO3gvdKKIx6/t5E9Dz4s8F2HSXr6Wp/M8PsfjSR6P8bgWuu/jqcDjfaB0EtTO85oYj5t4XMY64O9eVKW9/E6QO81zRtbzLCic57lRfown+3gcY5K1PJlm+haM1Qhq/+1g71l1qCM8vmZxnAoG94Bi5g9Xxss8ke938BjMPs/cUHjSw7AynlSDzdMLXVhAjvC0jCHT/CWexjWrsgJIM+WgYEqNxgA/zBNH3HFQHEkdTlVSp1K5VNKTfCR5MvlsMpds6SRpKBknJ5tpLIVaSA9KLAsf7BE/9s7+qsv4q65EW9gg0Lqv4l+kXMW6rvK7rynYzVIW4GwliUu0Biyarm6rLAuuftN/7xmXrZ47HrBlNHTvXLnsTVg2D6XqXsfVcy+9zmk19Mp2WwXL5OH5D+gu+gIqRsvRQ7JzuxvbsjxZJN0qWUmGoDeEczNKM0hqBk4zYcxhOjE/Lecmm8KYYp09ZXmDtnK4EvdUYrkSA7CswVzA0owjJT1cUNBkxma3e4knYrej5f7mFINVG0m2LIlAgq+FLFzrn/GxfQPJBLN04jGynLzb+M6Mz8e88zBv2Q2zncL2TUE6ZXm4olzianEFbKq47xUSzkxKpxaz37d8BX5dvjVSumduLtPgD/esDHRVZuctX9PeU3Y43VlZXLbRtaRy9cHf3Ft9U6X9SGCTj76QvXJT4+wBvrTbUChmFzdurZE2SAVWHea+VRz02XMse15Nt8zlcSRzaURSHNkQswjELERfQg6I2pBc+s9mfAzOqcyDmcRqc9tIcjafXZT9cDanc4cder2jBJVgabhkrORSCS2B6DxRvzbMnnJW8dKwC4cfgPyLIi6XVojwRm2zyapGJ2Mho3g8u+Cces3nNc6oc84CYjHnEZZNVlgWIrLcD0HKxXhJOrE4ITKYs9Tu7sqrq5NyslbfGC3d872+ktcmG+/dWDX3UGVzBY+/afKE8VsZa+7bukqjS9FWGmzWNPkbz9xx+cPC7kf3tuDj3pvuWrfurpu87K9hZih1/qQ5jAqR8jRKA9M9OmO4yFxlJtlmnMw+lgaDEVuNxWPFGBUbi6eKp4u5qrHiS8WkmLlq9pSFvcXYWIwjxXigeLh4tJgyxhOOJWFVwJNpDSNHw3A+RvnGfCF/Kv9c/nS+VpfvihQih8WYH8lcYsnTaPiWFLZ6/CY/Wz4+2GTYC/mWhYktHnYI7TK+061m4i7YJB4MKTZJov6FNQQ7ptwtQpiSrmViHMKYEntk/fr85Z2rXbvntt/d3G6vlZZn7Jvru+0Q9tHL6YWewjRjfl5mXt3XGmeP8qWlPOlu7dDq9NxsJsM0BIpCAlUbIhmadSgT5aLjcitaq095JOXxFPp+ypUUsj8Fp/ANerPHTBrNG8yPmK+YOYZVmx83P2t+36w1muWqVWGzg3OYHaTqIwcedWAScYw5FMeUgxsFgDhY1ErLwuoz26Y+ZWOaMaxpNXA5kVyDmY9kWeL5B4LjYXHpYcnD+I6HHUyzb0AKgZXE4pLYTIQFh16Lxl2mvEKrtSDPZMorsFoL80wp35vjxw5gD3d+MRWkrjQz1yH9l7JVUgS+G2GVJKP75UJNgwdhPcIrN6Dt6C70COJsUKk9i15BHMMeh9pR/6Ie65kbtaEwe8r2yurwqB4TpDfqI/oxvaKf0mtHAbikp/qE36pgKvgLuQQhTYQmfMVxRz0eSCDxMxicdF1zaifzYQyHQlcnCyyG2dLysJNr6LPyAa4CX6j4qIJoKiwVrgrKleML5R+VE025pdxVTvUF+P2CKwVksuBsASkQdGlhfSF+v/BKIZksPFtIChmFc+ML7o/cROO2uF1uyrnwBddHLqJxWVwuF9Vn4fezrmSRyayzWSRL1WDF71uvWMmk9ayVWBklaWL+F7I+JS+MtSatU0uNE/O/k8/BZqMmrKO6/IaiosrsBm3m0UySkimFpL0SKZKwWcJaCX9yQcL/KeEnpRcl8n0JPyjheyQ8JOGNEm5jAlbJDT24DyX8ovSGdEGiZyR8UsLLpZukLaDoqKTJl7BVwpyEP5Lwb6Q/S+RFCR+VfiKR/RLeK+EOCZdLAYm4JZyhiv3icny4NyT6Q3XA+yS8W8J9Eo5IuE7C+RIsrrgoSP5Bwm9I+GUJS/DGKWedPhNukTZKJMBMAFHVQqLy5k/+KPx96YxEFqu8KaEvbuExZt9liZ6UmAH0qIT3M5G9qj63tFwiRMqQCDjy57i/5CdM5EGJMH/3SnRhwMvMqgsSeVkNxlE1XMx8UFPGRjJL+RLtv5SQGoLhiMzozBYK6t+WsCJNSaRP2i+dlGgkbmVAosaFSJ5jBuDHJTyqGlktbZeIEFdNKlWtMWlMIjBHMptKcFHe8CA4dUH6SOKG2eQNqWOWS9im6oR5npIwMUoRaUAalhRJY5CwDvkbBioxqsSVVZEaQ2Z2fpFfUxkpsC636JxOe0uaEfl8pS0alj19xl/Gb37/TJaaQlkGhYTZc3090t11XdVyHbnnSxjXdfGodM9i5vUCX+yc4BrfgPzNKgMoA3qgDkBdHgx1wC72jX+uxzBL79asL03y1r+R9O03tLTlB/fkCp29Pe7l0Vrxjrn2Q43tOcFgrcV0eK7uYHu7fVV1RcbhuZtuuw1n0hjL/+VVGQWCedEpEG3t0KWkcctXX8PVU4G/mhoJcs6towrkGScqQ6Py5m3eO7xEm4v3mx40Ea0J79c/qCcUXvO0GCcvCaf7ZB9GvmEfqQIg4hvwjfrO+S75NHGANvmwx8rZG5DT6BSc55wcm+BInm1pJNNaXNDMJRtRhBpQvMJip4CPnZHstOxSM2P85aR74Y03E4KxEDz1UHAX5NFcrAYKx4usJFMehuLq2HasI5aqurXu6KGN/vL+727z7/JDJYhPzsm3kb4lq7ury3a4i7f4999Ot/ClKzJyLanSXU/tHXz63pBen+pw2pPnsr3ebHrjltENxSbjrEmX/DbLw23zH5BfQ3wq0Pfk/LW+ER/5uuWQhay0rrXeaR2xchq/xe/y05qcdTlfzzmUwxGWFrOS08J52cmpYZdstIRdrswQWiGswCvYAVGW5ww3rehZcXoFLQ3Z9Xp7ZqmmOOIsdwfcxO12Go0RTbk+oD+ppwKcQXoN1FxQq8MLbW3i/bYKe/1QccEqhmBBbQqVhKcLqcVX4uAsqPBnqVGBQlQbP0WtWRYowjEEDAo0Lfl1QduBbu+GG1emlS5zbKzr2lwcWL9hfaB4aetgMHBPjbc4p9Pf3F4cjN4cDRZjXe22xiK9waj573vthc3tvtUluXnums56uS8gZqa+uiMrOxJYWl2UJxTJN6u/UCY554JovW773NG5Y7r0L/ySt558wP5Os/Anm/9fTfNz9hYPb66D8effa5+X4/7I3nv/sUYPo/Dn8MhVfQiZSRWrB+IN4CLtIhz4zqv9clGbGu31uAWgu5EGwmtEXvZ7IqeHXlQNdxLgFGEOqhQ0hR5NwBgJ6BsJmKB0NJCAKbx/rUzA3CIZDbKjvASsBQihdWgb2og2o92oFw0BvBPdilpVfBvagm5SocEEXUDL0FLIOSvgXo5WA30T8G9FfaqUgErh+2X6hEUaWwDaivagW4C/++9K1wNlAN2hYltRP8gI8NawCWpDAfnAEmaLoOrsg2dY1VIC0BrQswmsFNRfK2+B5zUNgyq2GZ5slL1q36Wq5WtQHQqCttUwD2tQE7oRqNtU+V74DqlWMl93qLZvB9pOsPFvjZ/4zX7eyf4/4IttPDn2PE6CWaxV75OYkzvw9Cw+O4uFWbzvCo5cwcMfjn5I/nKpyHH60uQl0nSx5+Lpi7TsIjZchEN6xjgTmYnNDMyMzWhTDB/gVPQ+Nv1xutJx3v9u+3v+d9rRu7gm8u7wu8q7lCWyznd1+tC7mLa/Q60O45QwVTY1MDU8dW5qeurSlG74+dHnyU+f8zoMzzmeI44nmp7Y9wSNPYYNjzkeI5FHYo+Q0ePYcNxx3HucfufhpY6HG/IcDx0tcEwfvXSUMPUVR9NMoZ5v433fPPJNMnDf8H2j99HhA6MHyOm9k3vJYKTIsfNWj+PWhmIH789uT/LTdi2dV185AhtdhaFYj+zoAaENnWWOzoYiR6Y/o10DxnIgaKAOWkub6E56hE7SJF1LJM/RDN/pyKUIMTQ5mrxN6l8TehudoGjtwNrhtXRNqMgRbqh0GBocDd6Gsw3nGy42aHsa8An4hE6HJkNUDhV5Q3Iozxmyh23tVr+l3eg3tBOM2rEftXsN8wZiMPQY9hnYAYjIsBVr8AQeHW9r9XgaJ5LmWxoVXWSDgh9QXK3sLjd3KtoHFNTeuSE6jvG/dBw4fBjV5TYqvtaoEsvtaFT6AJAZMAyAMXfciuo6BgeHPKzBSweAe+COPHuA1D0YJyLPAht5BvHgIBocxB7GU0GgoEEPIzMK64OhZ/cgYjfG9ahSDBoczO7+X+i/dLEKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8L1R5cGUgL0ZvbnREZXNjcmlwdG9yCi9Gb250TmFtZSAvTGliZXJhdGlvblNlcmlmCi9GbGFncyA0Ci9Bc2NlbnQgODkxLjExMzI4Ci9EZXNjZW50IC0yMTYuMzA4NTkKL1N0ZW1WIDY4Ljg0NzY1NgovQ2FwSGVpZ2h0IDY1NC43ODUxNgovSXRhbGljQW5nbGUgMAovRm9udEJCb3ggWy0xNzYuNzU3ODEgLTMwMy4yMjI2NiAxMDA2LjgzNTk0IDk4MS40NDUzMV0KL0ZvbnRGaWxlMiA4IDAgUj4+CmVuZG9iagoxMCAwIG9iago8PC9UeXBlIC9Gb250Ci9Gb250RGVzY3JpcHRvciA5IDAgUgovQmFzZUZvbnQgL0xpYmVyYXRpb25TZXJpZgovU3VidHlwZSAvQ0lERm9udFR5cGUyCi9DSURUb0dJRE1hcCAvSWRlbnRpdHkKL0NJRFN5c3RlbUluZm8gPDwvUmVnaXN0cnkgKEFkb2JlKQovT3JkZXJpbmcgKElkZW50aXR5KQovU3VwcGxlbWVudCAwPj4KL1cgWzAgWzM2NS4yMzQzOCAwIDAgMjUwXSAzOSBbNzIyLjE2Nzk3XSA0MSA1MSA1NTYuMTUyMzQgNTUgWzYxMC44Mzk4NF0gNjggNzIgNDQzLjg0NzY2IDc1IFs1MDAgMjc3LjgzMjAzIDAgMCAyNzcuODMyMDMgNzc3LjgzMjAzIDAgMCA1MDAgMCAwIDM4OS4xNjAxNl1dCi9EVyAwPj4KZW5kb2JqCjExIDAgb2JqCjw8L0ZpbHRlciAvRmxhdGVEZWNvZGUKL0xlbmd0aCAyOTI+PiBzdHJlYW0KeJxdkdtqhDAQhu/zFHO5vVg87wFEaC0LXvRAbR9Ak9EGagwxXvj2TTK7W2hA4XP+f/wzE9XNc6OkhejdzLxFC4NUwuAyr4Yj9DhKxZIUhOT2SuHNp06zyJnbbbE4NWqYWVkCRB+uulizwe5RzD0+sOjNCDRSjbD7qlvH7ar1D06oLMSsqkDg4Dq9dPq1mxCiYNs3wtWl3fbO86f43DRCGjihNHwWuOiOo+nUiKyM3amgvLhTMVTiX/1Mrn7g350J6syp4ziNK0/pMVCeE52JDoEyUhakzEhZkNIZPB0SohNREagg35F8xYEoC+muOdJbqvsl8if6dU2dTtT3cksQPtbXFmTyd/U7uQ+Sr8a4GYbFheH5sUmF993qWXuXf34Bbb+WbgplbmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTAKL0Jhc2VGb250IC9MaWJlcmF0aW9uU2VyaWYKL0VuY29kaW5nIC9JZGVudGl0eS1ICi9EZXNjZW5kYW50Rm9udHMgWzEwIDAgUl0KL1RvVW5pY29kZSAxMSAwIFI+PgplbmRvYmoKeHJlZgowIDEyCjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAwNDI3IDAwMDAwIG4gCjAwMDAwMDAxNTQgMDAwMDAgbiAKMDAwMDAwNzgwNyAwMDAwMCBuIAowMDAwMDAwMTkxIDAwMDAwIG4gCjAwMDAwMDA2MzUgMDAwMDAgbiAKMDAwMDAwMDY5MCAwMDAwMCBuIAowMDAwMDAwNzM3IDAwMDAwIG4gCjAwMDAwMDY4NDUgMDAwMDAgbiAKMDAwMDAwNzA4NSAwMDAwMCBuIAowMDAwMDA3NDQ0IDAwMDAwIG4gCnRyYWlsZXIKPDwvU2l6ZSAxMgovUm9vdCA3IDAgUgovSW5mbyAxIDAgUj4+CnN0YXJ0eHJlZgo3OTQ3CiUlRU9G";
  }
```

but when i try to do an api call and append the result to pdfSrc its not working and throwing below error

document-generator.component.html:66 ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at NgxExtendedPdfViewerComponent.set (https://localhost:4000/doc-generator-doc-generator-module-ngfactory.js:10293:34)
    at updateProp (https://localhost:4000/vendor.js:52967:35)
    at checkAndUpdateDirectiveDynamic (https://localhost:4000/vendor.js:52689:17)
    at checkAndUpdateNodeDynamic (https://localhost:4000/vendor.js:61896:14)
    at checkAndUpdateNode (https://localhost:4000/vendor.js:61803:12)
    at debugCheckAndUpdateNode (https://localhost:4000/vendor.js:62698:36)
    at debugCheckDirectivesFn (https://localhost:4000/vendor.js:62643:9)
    at Object.updateDirectives (https://localhost:4000/doc-generator-doc-generator-module-ngfactory.js:48033:3499)
    at Object.debugUpdateDirectives [as updateDirectives] (https://localhost:4000/vendor.js:62631:19)
    at checkAndUpdateView (https://localhost:4000/vendor.js:61734:12)

**Comment by Nabeel-Zafar** [comment]
I am facing the same issue in angular 10

**Comment by stephanrauh** [comment]
Lunch break was too short to publish the new version. But I believe I've found and solved the bug.

**Comment by Nabeel-Zafar** [comment]
@stephanrauh what is it?

**Comment by stephanrauh** [comment]
I wasn't aware that the `[base64]` attribute is assigned `undefined`. Adding a guard solves the problem. However, when I tried, the PDF doesn't render until I toggle the sidebar. I hope I can solve this, too.

**Comment by Nabeel-Zafar** [comment]
@stephanrauh can you please share your code here?

**Comment by stephanrauh** [comment]
Done!

**Comment by sarpavardhan** [comment]
Hi @stephanrauh I tried installing 9.0.0-alpha.4 but its saying no matching version found.

**Comment by stephanrauh** [comment]
That's correct. My lunch break was too short to publish the version.

**Comment by sarpavardhan** [comment]
Ok, Thank you. I'll be waiting for the update.

**Comment by stephanrauh** [comment]
Your wait is over. Version 9.0.0-alpha.4 has landed. Enjoy!

**Comment by sarpavardhan** [comment]
I'm getting the below error when i'm tryign to install the updated version

![image](https://user-images.githubusercontent.com/33492875/116444466-9a30e600-a809-11eb-85a5-45d5dcf58acc.png)

Command i used `npm install ngx-extended-pdf-viewer@9.0.0-alpha.4`

**Comment by stephanrauh** [comment]
@sarpavardhan Maybe you've been too quick. As far as I know, npm is a distributed database, and it takes some time to publish changes to every node. Please try again. As far as I can see, the alpha.4 version is online.

**Comment by sarpavardhan** [comment]
@stephanrauh Thank you so much this is working now.
