### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\dist\ngx-extended-pdf-viewer\assets\pdf-2.2.199.js'

### ISSUE THREAD

**Issue by Rambj** [stephanrauh/ngx-extended-pdf-viewer#94]
When i run in angular(ng serve), it is giving following error

Error: ENOENT: no such file or
directory, open 'C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\dist\ngx-extended-pdf-viewer\assets\pdf-2.2.199.js'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Storage.provideSync (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@ngtools\webpack\src\compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:54)
    at Promise (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at hook (C:\Users\THOUGHTWAVE\angular-projects\ngx-extended-pdf-viewer-master\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:67:43)

**Comment by stephanrauh** [comment]
Look like an error during compile time. I can only guess, but I'd say you've referenced `dist\ngx-extended-pdf-viewer\assets\pdf-2.2.199.js` in the `angular.json`. However, it should be something like  `node_modules\ngx-extended-pdf-viewer\assets\pdf-2.2.199.js`. The `dist` folder only exists on my laptop. It's created when I'm compiling the library itself. Most likely you're just using it via npm (as opposed to compiling it yourself), so the files are in the `node_modules` folder.
